# Generated by Django 2.1.7 on 2020-06-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
